server:
  port: 7445

spring:
  datasource:
    url: jdbc:mysql://192.168.73.141:3306/monitor
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  config: classpath:logback-spring.xml

#日志配置
log:
  #  日志级别
  level: info
  #  日志路径
  path: /logs
  #  日志编码
  charset: UTF-8
  #  日志文件最大大小
  maxFileSize: 100MB
  #  日志保存天数
  maxHistory: 15

